server:
  port: 9001
#  servlet:
#    session:
#      timeout: 30m
spring:
  application:
    # 服务名
    name: gulimall-product
  # 数据源信息
  datasource:
    username: root
    password: root
    url: jdbc:mysql://119.3.54.144:3306/gulimall_pms?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
  # nacos服务
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848

mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  #设置实体类的自增主键
  global-config:
    db-config:
      id-type: auto
      #逻辑删除
#      logic-delete-value: 1
#      logic-not-delete-value: 0
#
#logging:
#  level:
#    com.chinasoft: error
